from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget
import sys, lines

list = lines.writ()

def main():
    app = QApplication(sys.argv)
    import tclear
    win = QMainWindow()
    win.resize(1600, 860)
    win.setCentralWidget(tclear.centralwidget)


    tclear.pushButton.clicked.connect(lambda :example(tclear.pushButton.text()))
    tclear.pushButton_18.clicked.connect(lambda :example(tclear.pushButton_18.text()))
    tclear.pushButton_19.clicked.connect(lambda :example(tclear.pushButton_19.text()))
    tclear.pushButton_20.clicked.connect(lambda :example(tclear.pushButton_20.text()))
    tclear.pushButton_31.clicked.connect(lambda :example(tclear.pushButton_31.text()))
    tclear.pushButton_32.clicked.connect(lambda :example(tclear.pushButton_32.text()))
    tclear.pushButton_33.clicked.connect(lambda :example(tclear.pushButton_33.text()))
    tclear.pushButton_34.clicked.connect(lambda :example(tclear.pushButton_34.text()))
    tclear.pushButton_35.clicked.connect(lambda :example(tclear.pushButton_35.text()))
    tclear.pushButton_36.clicked.connect(lambda :example(tclear.pushButton_36.text()))
    tclear.pushButton_37.clicked.connect(lambda :example(tclear.pushButton_37.text()))
    tclear.pushButton_38.clicked.connect(lambda :example(tclear.pushButton_38.text()))
    tclear.pushButton_49.clicked.connect(lambda :example(tclear.pushButton_49.text()))
    tclear.pushButton_50.clicked.connect(lambda :example(tclear.pushButton_50.text()))
    tclear.pushButton_51.clicked.connect(lambda :example(tclear.pushButton_51.text()))
    tclear.pushButton_52.clicked.connect(lambda :example(tclear.pushButton_52.text()))
    tclear.pushButton_53.clicked.connect(lambda :example(tclear.pushButton_53.text()))
    tclear.pushButton_54.clicked.connect(lambda :example(tclear.pushButton_54.text()))
    tclear.pushButton_55.clicked.connect(lambda :example(tclear.pushButton_55.text()))
    tclear.pushButton_56.clicked.connect(lambda :example(tclear.pushButton_56.text()))
    tclear.pushButton_57.clicked.connect(lambda :example(tclear.pushButton_57.text()))
    tclear.pushButton_58.clicked.connect(lambda :example(tclear.pushButton_58.text()))
    tclear.pushButton_59.clicked.connect(lambda :example(tclear.pushButton_59.text()))
    tclear.pushButton_60.clicked.connect(lambda :example(tclear.pushButton_60.text()))
    tclear.pushButton_61.clicked.connect(lambda :example(tclear.pushButton_61.text()))
    tclear.pushButton_62.clicked.connect(lambda :example(tclear.pushButton_62.text()))
    tclear.pushButton_63.clicked.connect(lambda :example(tclear.pushButton_63.text()))
    tclear.pushButton_64.clicked.connect(lambda :example(tclear.pushButton_64.text()))
    tclear.pushButton_65.clicked.connect(lambda :example(tclear.pushButton_65.text()))
    tclear.pushButton_66.clicked.connect(lambda :example(tclear.pushButton_66.text()))
    tclear.pushButton_67.clicked.connect(lambda :example(tclear.pushButton_67.text()))
    tclear.pushButton_68.clicked.connect(lambda :example(tclear.pushButton_68.text()))
    tclear.pushButton_69.clicked.connect(lambda :example(tclear.pushButton_69.text()))
    tclear.pushButton_70.clicked.connect(lambda :example(tclear.pushButton_70.text()))
    tclear.pushButton_71.clicked.connect(lambda :example(tclear.pushButton_71.text()))
    tclear.pushButton_72.clicked.connect(lambda :example(tclear.pushButton_72.text()))
    tclear.pushButton_73.clicked.connect(lambda :example(tclear.pushButton_73.text()))
    tclear.pushButton_74.clicked.connect(lambda :example(tclear.pushButton_74.text()))
    tclear.pushButton_75.clicked.connect(lambda :example(tclear.pushButton_75.text()))
    tclear.pushButton_76.clicked.connect(lambda :example(tclear.pushButton_76.text()))
    tclear.pushButton_77.clicked.connect(lambda :example(tclear.pushButton_77.text()))
    tclear.pushButton_78.clicked.connect(lambda :example(tclear.pushButton_78.text()))
    tclear.pushButton_79.clicked.connect(lambda :example(tclear.pushButton_79.text()))
    tclear.pushButton_80.clicked.connect(lambda :example(tclear.pushButton_80.text()))
    tclear.pushButton_81.clicked.connect(lambda :example(tclear.pushButton_81.text()))
    tclear.pushButton_82.clicked.connect(lambda :example(tclear.pushButton_82.text()))
    tclear.pushButton_83.clicked.connect(lambda :example(tclear.pushButton_83.text()))
    tclear.pushButton_84.clicked.connect(lambda :example(tclear.pushButton_84.text()))
    tclear.pushButton_85.clicked.connect(lambda :example(tclear.pushButton_85.text()))
    tclear.pushButton_86.clicked.connect(lambda :example(tclear.pushButton_86.text()))
    tclear.pushButton_87.clicked.connect(lambda :example(tclear.pushButton_87.text()))
    tclear.pushButton_88.clicked.connect(lambda :example(tclear.pushButton_88.text()))
    tclear.pushButton_89.clicked.connect(lambda :example(tclear.pushButton_89.text()))
    tclear.pushButton_90.clicked.connect(lambda :example(tclear.pushButton_90.text()))
    tclear.pushButton_91.clicked.connect(lambda :example(tclear.pushButton_91.text()))
    tclear.pushButton_92.clicked.connect(lambda :example(tclear.pushButton_92.text()))
    tclear.pushButton_93.clicked.connect(lambda :example(tclear.pushButton_93.text()))
    tclear.pushButton_94.clicked.connect(lambda :example(tclear.pushButton_94.text()))
    tclear.pushButton_95.clicked.connect(lambda :example(tclear.pushButton_95.text()))
    tclear.pushButton_96.clicked.connect(lambda :example(tclear.pushButton_96.text()))
    tclear.pushButton_97.clicked.connect(lambda :example(tclear.pushButton_97.text()))
    tclear.pushButton_98.clicked.connect(lambda :example(tclear.pushButton_98.text()))
    tclear.pushButton_99.clicked.connect(lambda :example(tclear.pushButton_99.text()))
    tclear.pushButton_100.clicked.connect(lambda :example(tclear.pushButton_100.text()))
    tclear.pushButton_101.clicked.connect(lambda :example(tclear.pushButton_101.text()))
    tclear.pushButton_102.clicked.connect(lambda :example(tclear.pushButton_102.text()))
    tclear.pushButton_103.clicked.connect(lambda :example(tclear.pushButton_103.text()))
    tclear.pushButton_104.clicked.connect(lambda :example(tclear.pushButton_104.text()))
    tclear.pushButton_105.clicked.connect(lambda :example(tclear.pushButton_105.text()))
    tclear.pushButton_106.clicked.connect(lambda :example(tclear.pushButton_106.text()))
    tclear.pushButton_107.clicked.connect(lambda :example(tclear.pushButton_107.text()))
    tclear.pushButton_108.clicked.connect(lambda :example(tclear.pushButton_108.text()))
    tclear.pushButton_109.clicked.connect(lambda :example(tclear.pushButton_109.text()))
    tclear.pushButton_110.clicked.connect(lambda :example(tclear.pushButton_110.text()))
    tclear.pushButton_111.clicked.connect(lambda :example(tclear.pushButton_111.text()))
    tclear.pushButton_112.clicked.connect(lambda :example(tclear.pushButton_112.text()))
    tclear.pushButton_113.clicked.connect(lambda :example(tclear.pushButton_113.text()))
    tclear.pushButton_114.clicked.connect(lambda :example(tclear.pushButton_114.text()))
    tclear.pushButton_115.clicked.connect(lambda :example(tclear.pushButton_115.text()))
    tclear.pushButton_116.clicked.connect(lambda :example(tclear.pushButton_116.text()))
    tclear.pushButton_117.clicked.connect(lambda :example(tclear.pushButton_117.text()))
    tclear.pushButton_118.clicked.connect(lambda :example(tclear.pushButton_118.text()))
    tclear.pushButton_119.clicked.connect(lambda :example(tclear.pushButton_119.text()))
    tclear.pushButton_120.clicked.connect(lambda :example(tclear.pushButton_120.text()))
    tclear.pushButton_121.clicked.connect(lambda :example(tclear.pushButton_121.text()))
    tclear.pushButton_122.clicked.connect(lambda :example(tclear.pushButton_122.text()))
    tclear.pushButton_123.clicked.connect(lambda :example(tclear.pushButton_123.text()))
    tclear.pushButton_124.clicked.connect(lambda :example(tclear.pushButton_124.text()))
    tclear.pushButton_125.clicked.connect(lambda :example(tclear.pushButton_125.text()))
    tclear.pushButton_126.clicked.connect(lambda :example(tclear.pushButton_126.text()))
    tclear.pushButton_130.clicked.connect(lambda :example(tclear.pushButton_130.text()))
    tclear.pushButton_131.clicked.connect(lambda :example(tclear.pushButton_131.text()))
    tclear.pushButton_132.clicked.connect(lambda :example(tclear.pushButton_132.text()))
    tclear.pushButton_133.clicked.connect(lambda :example(tclear.pushButton_133.text()))
    tclear.pushButton_134.clicked.connect(lambda :example(tclear.pushButton_134.text()))
    tclear.pushButton_135.clicked.connect(lambda :example(tclear.pushButton_135.text()))
    tclear.pushButton_136.clicked.connect(lambda :example(tclear.pushButton_136.text()))
    tclear.pushButton_137.clicked.connect(lambda :example(tclear.pushButton_137.text()))
    tclear.pushButton_138.clicked.connect(lambda :example(tclear.pushButton_138.text()))
    tclear.pushButton_139.clicked.connect(lambda :example(tclear.pushButton_139.text()))
    tclear.pushButton_140.clicked.connect(lambda :example(tclear.pushButton_140.text()))
    tclear.pushButton_141.clicked.connect(lambda :example(tclear.pushButton_141.text()))
    tclear.pushButton_142.clicked.connect(lambda :example(tclear.pushButton_142.text()))
    tclear.pushButton_143.clicked.connect(lambda :example(tclear.pushButton_143.text()))
    tclear.pushButton_148.clicked.connect(lambda :example(tclear.pushButton_148.text()))
    tclear.pushButton_149.clicked.connect(lambda :example(tclear.pushButton_149.text()))
    tclear.pushButton_150.clicked.connect(lambda :example(tclear.pushButton_150.text()))
    tclear.pushButton_151.clicked.connect(lambda :example(tclear.pushButton_151.text()))
    tclear.pushButton_152.clicked.connect(lambda :example(tclear.pushButton_152.text()))
    tclear.pushButton_153.clicked.connect(lambda :example(tclear.pushButton_153.text()))
    tclear.pushButton_154.clicked.connect(lambda :example(tclear.pushButton_154.text()))
    tclear.pushButton_155.clicked.connect(lambda :example(tclear.pushButton_155.text()))
    tclear.pushButton_156.clicked.connect(lambda :example(tclear.pushButton_156.text()))
    tclear.pushButton_157.clicked.connect(lambda :example(tclear.pushButton_157.text()))
    tclear.pushButton_158.clicked.connect(lambda :example(tclear.pushButton_158.text()))
    tclear.pushButton_159.clicked.connect(lambda :example(tclear.pushButton_159.text()))
    tclear.pushButton_160.clicked.connect(lambda :example(tclear.pushButton_160.text()))
    tclear.pushButton_161.clicked.connect(lambda :example(tclear.pushButton_161.text()))

    win.show()
    sys.exit(app.exec())


def example(info):
    import tclear
    
    info = info.split(' ')
    tclear.label_2.setText(str(list[int(info[1])-1]))

main()