# Form implementation generated from reading ui file 'notification.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 246)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(150, 40, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.MainLabel.setFont(font)
        self.MainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MainLabel.setObjectName("MainLabel")
        self.SecondLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.SecondLabel.setGeometry(QtCore.QRect(10, 90, 741, 61))
        self.SecondLabel.setObjectName("SecondLabel")
        self.AdminKeyEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.AdminKeyEdit.setGeometry(QtCore.QRect(40, 170, 241, 41))
        self.AdminKeyEdit.setObjectName("AdminKeyEdit")
        self.AdminKEyLAbel = QtWidgets.QLabel(parent=self.centralwidget)
        self.AdminKEyLAbel.setGeometry(QtCore.QRect(50, 150, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.AdminKEyLAbel.setFont(font)
        self.AdminKEyLAbel.setObjectName("AdminKEyLAbel")
        self.Submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(290, 170, 111, 41))
        self.Submit.setObjectName("Submit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainLabel.setText(_translate("MainWindow", "Добро пожаловать"))
        self.SecondLabel.setText(_translate("MainWindow", "Срок действия вашего гостевого пропуска истёк. Пожалйста позовите администратора."))
        self.AdminKEyLAbel.setText(_translate("MainWindow", "Ключ администратора:"))
        self.Submit.setText(_translate("MainWindow", "Ввод"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
