# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 237)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(60, 0, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Label.setObjectName("Label")
        self.NameEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NameEntry.setGeometry(QtCore.QRect(140, 70, 181, 31))
        self.NameEntry.setObjectName("NameEntry")
        self.Label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_2.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.Label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Label_2.setObjectName("Label_2")
        self.Label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_3.setGeometry(QtCore.QRect(20, 130, 111, 31))
        self.Label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Label_3.setObjectName("Label_3")
        self.SecondNameEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.SecondNameEntry.setGeometry(QtCore.QRect(140, 130, 181, 31))
        self.SecondNameEntry.setObjectName("SecondNameEntry")
        self.Submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(200, 190, 161, 31))
        self.Submit.setObjectName("Submit")
        self.Error1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error1.setGeometry(QtCore.QRect(70, 50, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Error1.setFont(font)
        self.Error1.setObjectName("Error1")
        self.Error2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error2.setGeometry(QtCore.QRect(70, 110, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Error2.setFont(font)
        self.Error2.setObjectName("Error2")
        self.Confirm = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Confirm.setGeometry(QtCore.QRect(60, 170, 401, 18))
        self.Confirm.setObjectName("Confirm")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label.setText(_translate("MainWindow", "Регистрация нового сотрудника"))
        self.Label_2.setText(_translate("MainWindow", "Имя:"))
        self.Label_3.setText(_translate("MainWindow", "Фамилия:"))
        self.Submit.setText(_translate("MainWindow", "Ввод"))
        self.Error1.setText(_translate("MainWindow", "*Поле не заполнено/ заполнено неправильно"))
        self.Error2.setText(_translate("MainWindow", "*Поле не заполнено/ заполнено неправильно"))
        self.Confirm.setText(_translate("MainWindow", "Подтверждаю правильность введенных данных"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
