from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
font = QtGui.QFont()
font.setPointSize(12)
centralwidget.setFont(font)
centralwidget.setObjectName("centralwidget")
label = QtWidgets.QLabel(parent=centralwidget)
label.setGeometry(QtCore.QRect(190, 10, 191, 41))
label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
label.setObjectName("label")
label_2 = QtWidgets.QLabel(parent=centralwidget)
label_2.setGeometry(QtCore.QRect(-10, 100, 131, 41))
label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
label_2.setObjectName("label_2")
label_3 = QtWidgets.QLabel(parent=centralwidget)
label_3.setGeometry(QtCore.QRect(-10, 150, 131, 41))
label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
label_3.setObjectName("label_3")
label_4 = QtWidgets.QLabel(parent=centralwidget)
label_4.setGeometry(QtCore.QRect(30, 200, 271, 41))
label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
label_4.setObjectName("label_4")
SecondName = QtWidgets.QLineEdit(parent=centralwidget)
SecondName.setGeometry(QtCore.QRect(130, 110, 421, 31))
SecondName.setObjectName("SecondName")
Name = QtWidgets.QLineEdit(parent=centralwidget)
Name.setGeometry(QtCore.QRect(130, 160, 421, 31))
Name.setObjectName("Name")
ID = QtWidgets.QLineEdit(parent=centralwidget)
ID.setGeometry(QtCore.QRect(310, 210, 241, 31))
ID.setObjectName("ID")
Error2 = QtWidgets.QLabel(parent=centralwidget)
Error2.setGeometry(QtCore.QRect(270, 90, 281, 21))
font = QtGui.QFont()
font.setPointSize(10)
Error2.setFont(font)
Error2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Error2.setObjectName("Error2")
Error3 = QtWidgets.QLabel(parent=centralwidget)
Error3.setGeometry(QtCore.QRect(270, 140, 281, 21))
font = QtGui.QFont()
font.setPointSize(10)
Error3.setFont(font)
Error3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Error3.setObjectName("Error3")
Error4 = QtWidgets.QLabel(parent=centralwidget)
Error4.setGeometry(QtCore.QRect(270, 190, 281, 21))
font = QtGui.QFont()
font.setPointSize(10)
Error4.setFont(font)
Error4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Error4.setObjectName("Error4")
Confirm = QtWidgets.QCheckBox(parent=centralwidget)
Confirm.setGeometry(QtCore.QRect(40, 310, 381, 51))
Confirm.setObjectName("Confirm")
Submit = QtWidgets.QPushButton(parent=centralwidget)
Submit.setGeometry(QtCore.QRect(220, 360, 151, 51))
Submit.setObjectName("Submit")
IfEntry = QtWidgets.QRadioButton(parent=centralwidget)
IfEntry.setGeometry(QtCore.QRect(50, 260, 61, 41))
IfEntry.setObjectName("IfEntry")
IfExit = QtWidgets.QRadioButton(parent=centralwidget)
IfExit.setGeometry(QtCore.QRect(130, 260, 81, 41))
IfExit.setObjectName("IfExit")
PlacesLeft = QtWidgets.QLabel(parent=centralwidget)
PlacesLeft.setGeometry(QtCore.QRect(230, 250, 251, 41))
PlacesLeft.setObjectName("PlacesLeft")
IfParking = QtWidgets.QCheckBox(parent=centralwidget)
IfParking.setGeometry(QtCore.QRect(230, 280, 251, 41))
IfParking.setObjectName("IfParking")
IfGuest = QtWidgets.QCheckBox(parent=centralwidget)
IfGuest.setGeometry(QtCore.QRect(60, 60, 61, 41))
IfGuest.setObjectName("IfGuest")
GuestTime = QtWidgets.QLineEdit(parent=centralwidget)
GuestTime.setGeometry(QtCore.QRect(130, 70, 113, 31))
GuestTime.setObjectName("GuestTime")
Error1 = QtWidgets.QLabel(parent=centralwidget)
Error1.setGeometry(QtCore.QRect(-40, 40, 281, 21))
font = QtGui.QFont()
font.setPointSize(10)
Error1.setFont(font)
Error1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Error1.setObjectName("Error1")
label_10 = QtWidgets.QLabel(parent=centralwidget)
label_10.setGeometry(QtCore.QRect(-40, 50, 281, 21))
font = QtGui.QFont()
font.setPointSize(10)
label_10.setFont(font)
label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
label_10.setObjectName("label_10")

label.setText("Запись входа/выхода")
label_2.setText("Фамилия:")
label_3.setText("Имя:")
label_4.setText("Номер индивидуального пропуска:")
Error2.setText("*Поле не заполнено/ заполнено неправильно")
Error3.setText("*Поле не заполнено/ заполнено неправильно")
Error4.setText("*Поле не заполнено/ заполнено неправильно")
Confirm.setText("Подтверждаю правильность введенных данных")
Submit.setText("Подтвердить")
IfEntry.setText("Вход")
IfExit.setText("Выход")
PlacesLeft.setText("Парковочных мест доступно: 10")
IfParking.setText("Выписать парковочный талон")
IfGuest.setText("Гость")
Error1.setText("*Поле не заполнено/ заполнено неправильно")
label_10.setText("Время действия пропуска(в часах)")