from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
font = QtGui.QFont()
font.setPointSize(12)
centralwidget.setFont(font)
centralwidget.setObjectName("centralwidget")
MainLabel = QtWidgets.QLabel(parent=centralwidget)
MainLabel.setGeometry(QtCore.QRect(150, 40, 391, 41))
font = QtGui.QFont()
font.setPointSize(20)
MainLabel.setFont(font)
MainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
MainLabel.setObjectName("MainLabel")
SecondLabel = QtWidgets.QLabel(parent=centralwidget)
SecondLabel.setGeometry(QtCore.QRect(10, 90, 741, 61))
SecondLabel.setObjectName("SecondLabel")
AdminKeyEdit = QtWidgets.QLineEdit(parent=centralwidget)
AdminKeyEdit.setGeometry(QtCore.QRect(40, 170, 241, 41))
AdminKeyEdit.setObjectName("AdminKeyEdit")
AdminKEyLAbel = QtWidgets.QLabel(parent=centralwidget)
AdminKEyLAbel.setGeometry(QtCore.QRect(50, 150, 201, 16))
font = QtGui.QFont()
font.setPointSize(9)
AdminKEyLAbel.setFont(font)
AdminKEyLAbel.setObjectName("AdminKEyLAbel")
Submit = QtWidgets.QPushButton(parent=centralwidget)
Submit.setGeometry(QtCore.QRect(290, 170, 111, 41))
Submit.setObjectName("Submit")

MainLabel.setText("Добро пожаловать")
SecondLabel.setText("Срок действия вашего гостевого пропуска истёк. Пожалйста позовите администратора.")
AdminKEyLAbel.setText("Ключ администратора:")
Submit.setText("Ввод")