from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
font = QtGui.QFont()
font.setPointSize(12)
centralwidget.setFont(font)
centralwidget.setObjectName("centralwidget")
Label = QtWidgets.QLabel(parent=centralwidget)
Label.setGeometry(QtCore.QRect(60, 0, 451, 71))
font = QtGui.QFont()
font.setPointSize(20)
Label.setFont(font)
Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
Label.setObjectName("Label")
NameEntry = QtWidgets.QLineEdit(parent=centralwidget)
NameEntry.setGeometry(QtCore.QRect(140, 70, 181, 31))
NameEntry.setObjectName("NameEntry")
Label_2 = QtWidgets.QLabel(parent=centralwidget)
Label_2.setGeometry(QtCore.QRect(20, 70, 111, 31))
Label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Label_2.setObjectName("Label_2")
Label_3 = QtWidgets.QLabel(parent=centralwidget)
Label_3.setGeometry(QtCore.QRect(20, 130, 111, 31))
Label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Label_3.setObjectName("Label_3")
SecondNameEntry = QtWidgets.QLineEdit(parent=centralwidget)
SecondNameEntry.setGeometry(QtCore.QRect(140, 130, 181, 31))
SecondNameEntry.setObjectName("SecondNameEntry")
Submit = QtWidgets.QPushButton(parent=centralwidget)
Submit.setGeometry(QtCore.QRect(200, 190, 161, 31))
Submit.setObjectName("Submit")
Error1 = QtWidgets.QLabel(parent=centralwidget)
Error1.setGeometry(QtCore.QRect(70, 50, 341, 21))
font = QtGui.QFont()
font.setPointSize(9)
Error1.setFont(font)
Error1.setObjectName("Error1")
Error2 = QtWidgets.QLabel(parent=centralwidget)
Error2.setGeometry(QtCore.QRect(70, 110, 341, 21))
font = QtGui.QFont()
font.setPointSize(9)
Error2.setFont(font)
Error2.setObjectName("Error2")
Confirm = QtWidgets.QCheckBox(parent=centralwidget)
Confirm.setGeometry(QtCore.QRect(60, 170, 401, 18))
Confirm.setObjectName("Confirm")

Label.setText("Регистрация нового сотрудника")
Label_2.setText("Имя:")
Label_3.setText("Фамилия:")
Submit.setText("Ввод")
Error1.setText("*Поле не заполнено/ заполнено неправильно")
Error2.setText("*Поле не заполнено/ заполнено неправильно")
Confirm.setText("Подтверждаю правильность введенных данных")
