from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
centralwidget.setObjectName("centralwidget")
label = QtWidgets.QLabel(parent=centralwidget)
label.setGeometry(QtCore.QRect(210, 70, 371, 81))
font = QtGui.QFont()
font.setPointSize(26)
label.setFont(font)
label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
label.setObjectName("label")
lineEdit = QtWidgets.QLineEdit(parent=centralwidget)
lineEdit.setGeometry(QtCore.QRect(270, 230, 241, 31))
lineEdit.setObjectName("lineEdit")
label_2 = QtWidgets.QLabel(parent=centralwidget)
label_2.setGeometry(QtCore.QRect(270, 210, 251, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_2.setFont(font)
label_2.setObjectName("label_2")
pushButton = QtWidgets.QPushButton(parent=centralwidget)
pushButton.setGeometry(QtCore.QRect(330, 270, 121, 31))
font = QtGui.QFont()
font.setPointSize(12)
pushButton.setFont(font)
pushButton.setObjectName("pushButton")
label_3 = QtWidgets.QLabel(parent=centralwidget)
label_3.setGeometry(QtCore.QRect(290, 330, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_3.setFont(font)
label_3.setObjectName("label_3")
label_4 = QtWidgets.QLabel(parent=centralwidget)
label_4.setGeometry(QtCore.QRect(290, 360, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_4.setFont(font)
label_4.setObjectName("label_4")
label_5 = QtWidgets.QLabel(parent=centralwidget)
label_5.setGeometry(QtCore.QRect(290, 390, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_5.setFont(font)
label_5.setObjectName("label_5")
label_6 = QtWidgets.QLabel(parent=centralwidget)
label_6.setGeometry(QtCore.QRect(290, 420, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_6.setFont(font)
label_6.setObjectName("label_6")
label_7 = QtWidgets.QLabel(parent=centralwidget)
label_7.setGeometry(QtCore.QRect(290, 450, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_7.setFont(font)
label_7.setObjectName("label_7")
label_8 = QtWidgets.QLabel(parent=centralwidget)
label_8.setGeometry(QtCore.QRect(290, 480, 171, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_8.setFont(font)
label_8.setObjectName("label_8")
label_9 = QtWidgets.QLabel(parent=centralwidget)
label_9.setGeometry(QtCore.QRect(470, 330, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_9.setFont(font)
label_9.setText("")
label_9.setObjectName("label_9")
label_10 = QtWidgets.QLabel(parent=centralwidget)
label_10.setGeometry(QtCore.QRect(470, 360, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_10.setFont(font)
label_10.setText("")
label_10.setObjectName("label_10")
label_11 = QtWidgets.QLabel(parent=centralwidget)
label_11.setGeometry(QtCore.QRect(470, 390, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_11.setFont(font)
label_11.setText("")
label_11.setObjectName("label_11")
label_12 = QtWidgets.QLabel(parent=centralwidget)
label_12.setGeometry(QtCore.QRect(470, 420, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_12.setFont(font)
label_12.setText("")
label_12.setObjectName("label_12")
label_13 = QtWidgets.QLabel(parent=centralwidget)
label_13.setGeometry(QtCore.QRect(470, 450, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_13.setFont(font)
label_13.setText("")
label_13.setObjectName("label_13")
label_14 = QtWidgets.QLabel(parent=centralwidget)
label_14.setGeometry(QtCore.QRect(470, 480, 101, 21))
font = QtGui.QFont()
font.setPointSize(12)
label_14.setFont(font)
label_14.setText("")
label_14.setObjectName("label_14")

label.setText("Статистика бросков")
label_2.setText("Введите колличество итераций:")
pushButton.setText("Рассчитать")
label_3.setText("Процент выпадения 1:")
label_4.setText("Процент выпадения 2:")
label_5.setText("Процент выпадения 3:")
label_6.setText("Процент выпадения 4:")
label_7.setText("Процент выпадения 5:")
label_8.setText("Процент выпадения 6:")