from PyQt6 import QtWidgets, QtGui, QtCore


Window2 = QtWidgets.QWidget()
Window2.setObjectName("Window2")
label = QtWidgets.QLabel(parent=Window2)
label.setGeometry(QtCore.QRect(270, 90, 261, 101))
font = QtGui.QFont()
font.setPointSize(26)
label.setFont(font)
label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
label.setObjectName("label")
lineEdit = QtWidgets.QLineEdit(parent=Window2)
lineEdit.setGeometry(QtCore.QRect(290, 300, 211, 41))
font = QtGui.QFont()
font.setPointSize(12)
lineEdit.setFont(font)
lineEdit.setObjectName("lineEdit")
pushButton = QtWidgets.QPushButton(parent=Window2)
pushButton.setGeometry(QtCore.QRect(330, 350, 131, 31))
font = QtGui.QFont()
font.setPointSize(12)
pushButton.setFont(font)
pushButton.setObjectName("pushButton")
label_2 = QtWidgets.QLabel(parent=Window2)
label_2.setGeometry(QtCore.QRect(200, 380, 400, 30))
font = QtGui.QFont()
font.setPointSize(12)
label_2.setFont(font)
label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
label_2.setObjectName("label_2")
pushButton_2 = QtWidgets.QPushButton(parent=Window2)
pushButton_2.setGeometry(QtCore.QRect(230, 430, 151, 31))
font = QtGui.QFont()
font.setPointSize(12)
pushButton_2.setFont(font)
pushButton_2.setObjectName("pushButton_2")
pushButton_3 = QtWidgets.QPushButton(parent=Window2)
pushButton_3.setGeometry(QtCore.QRect(470, 430, 75, 31))
font = QtGui.QFont()
font.setPointSize(12)
pushButton_3.setFont(font)
pushButton_3.setObjectName("pushButton_3")

label.setText("Угадай число!")
pushButton.setText("Ввод")
label_2.setText("Неправильно, ответ был XXX!")
pushButton_2.setText("Сыграть ещё раз?")
pushButton_3.setText("Выйти!")